extends: "eslint:recommended"
root: true

env:
    es6: true

globals:
    # Needed until we produce our own eslint-gjs plugin.
    ARGV: false
    Debugger: false
    GjsFileImporter: false
    InternalError: false
    Iterator: false
    StopIteration: false
    imports: false
    log: false
    logError: false
    print: false
    printerr: false
    uneval: false
    window: false

    # From package.js
    C_: false
    N_: false
    _: false
    pkg: false

rules:
    no-unused-vars:
        - 0
    indent:
        - 2
        - 4
    no-var:
        - 2
